### PR TITLE
Allow sending 50m+ files to telegram channels using MTProto

### LINKED ISSUE #23: Allow >50M audio upload to telegram
With #19 and #15 in place, it was tested in a few real configurations and works as expected. However, the limitation of 50M for upload feels strange from the user's point of view and we need to allow such big files.

Recently, as a part of https://github.com/radio-t/gitter-rt-bot/issues/3 I've played with github.com/go-telegram-bot-api/telegram-bot-api library and it seems to provide complete support of all telegram's API functionality, for both bots as well as other parts. @sgaynetdinov - maybe switching to this lib may help you to complete the task.

### PR DESCRIPTION
**Pull request by paskal**
This PR switches the Telegram connector from [Bot API](https://core.telegram.org/bots/api) to the [Core API](https://core.telegram.org/api), resolves #23 and likely closes #31.

Before and after:
image
image

### CODE REVIEW

**Comment by ernado** [comment]
Hey @paskal, please consider using [gotd/td](https://github.com/gotd/td) as Telegram client, should be better maintained and probably more ergonomic.

**Comment by paskal** [comment]
I'll check it, but it's unlikely I will change the used library. The existing one already works except for HTML parsing, which I need to fix on this app side and which is unlikely solved in the library you mentioned.

**Comment by ernado** [comment]
Got it, thank you for reply.

I've added [comparison](https://github.com/gotd/td#difference-to-other-projects) that can help with trade-offs of picking one or other implementation.

**Comment by paskal** [comment]
I'll take a closer look into your library now, you got my attention.

**Comment by paskal** [comment]
@ernado @tdakkota I see that switch to that library would require complete code rewrite and is not trivial because the only real example is [gotd/bot](https://github.com/gotd/bot) source example. I still need to fix the incomplete HTML parsing logic I have for the currently used library; the [message module](https://pkg.go.dev/github.com/gotd/td/telegram/message) doesn't seem to solve that problem for me.

If you're interested in using that library for this particular use case, I propose you take my code and rewrite it for your library and send an MR to this repo; however, I personally do not want to spend another day on a rewrite of a working code for the sake of rewrite itself.

**Comment by ernado** [comment]
Ok, I'd better improve gotd examples and documentation.

Anyway it seems like switching from current library to gotd is a matter of time unless someone is going to spend several months fixing issues, introducing missing features and maintaining.

**Comment by paskal** [comment]
The trick is, you don't need to fix something which is not broken, and you don't need to introduce missing features if you already have all the required features on the table. I don't see where the necessity to "spend several months fixing issues" in `feed-master` comes from.

I am running a `feed-master` from this branch with the same config as one in production for two weeks by now, and it works as reliable as the current master. The only known problems are coming not from the library but from the way I parse the incoming HTML from the RSS feed. `gotd/td` doesn't solve this for me as well. For the file upload in `feed-master`, both libraries have feature parity.

**Comment by ernado** [comment]
Current library uses MTProto v1 that is deprecated and will be eventually disabled by Telegram in the future, so things can just stop working randomly, not considering that it is like using software that has open CVE.

I'm also going to quote xelaj/mtproto comment here:
https://github.com/xelaj/mtproto/blob/216789b95a5d644ebbdd1acb7eb46ff61647960a/internal/aes_ige/ige_cipher.go#L160-L161
> ЭТО ЕБАНАЯ МАГИЧЕСКАЯ ФУНКЦИЯ ОНА НАХУЙ РАБОТАЕТ ПРОСТО БЛЯТЬ НЕ ТРОГАЙ ШАКАЛ ЕБАНЫЙ

If you are ok with this, I'm done here.

**Comment by umputun** [comment]
let me clarify a little bit from my perspective. Sending 50+ Mb files is a nice to have feature, however, this is **not that essential** for the particular application. I think the time and efforts @paskal already invested into this task were a little bit too much for the end goal, but I can hardly see anyone "spend several months" to improve it or adopt any other library regardless of the ergonomics.

If v1 will be disabled by tg one day - well, so be it. Feed master can always do what it always did with the bot API, i.e. upload under 50m files only and put external links for the bigger file. And, who knows,  maybe as tg kill support of v1 they will increase the upload limits.

**Comment by ernado** [comment]
As alternative you can also host your own [local bot api](https://core.telegram.org/bots/api#using-a-local-bot-api-server) server, it is official and should be enough to send 50+ Mb files.

**Comment by paskal** [comment]
Rebased on top of current master just to show how much more complex it is rather than using the self-hosted bot API server we choose to go with. Closing this PR.

**Pull request closed without merging**
