### PR TITLE
Replace package 'gopkg.in/tucnak/telebot.v2' -> 'github.com/go-telegram-bot-api/telegram-bot-api'

### PR DESCRIPTION
**Pull request by sgaynetdinov**
#23 

NOTE: In file `_example/etc/fm.yml` replace `telegram_channel_slug` to `telegram_channel_id` (example: `telegram_channel: "-1001409915930"`)

[telegram-bot-how-to-get-a-group-chat-id](https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id/32572159#32572159)

### CODE REVIEW

**Comment by umputun** [comment]
sorry, I have missed this PR completely. Can you provide more context pls? From [this comment](https://github.com/umputun/feed-master/issues/23#issuecomment-573403030) I thought it doesn't fix 50M problem. Am I right?

**Comment by sgaynetdinov** [comment]
> sorry, I have missed this PR completely. Can you provide more context pls? From [this comment](https://github.com/umputun/feed-master/issues/23#issuecomment-573403030) I thought it doesn't fix 50M problem. Am I right?

> Am I right?
Yes, problem doesn't fix.
Load files >50M, this should help: https://habr.com/ru/post/348234/

In this PR https://github.com/radio-t/gitter-rt-bot/pull/5, is implemented this way (https://github.com/radio-t/gitter-rt-bot/pull/5#issuecomment-575923499)?

**Comment by chuhlomin** [comment]
> In this PR radio-t/gitter-rt-bot#5, is implemented this way (radio-t/gitter-rt-bot#5 (comment))?

It's not implemented in any way yet.

**Comment by paskal** [comment]
@sgaynetdinov as far as I see this change is unnecessary. You're changing one Telegram **Bot** API library for another when for large files upload we need Telegram API library

**Pull request closed without merging**
