### PR TITLE
Add page with available feeds

### PR DESCRIPTION
**Pull request by orthur**
Page view

Screenshot 2022-03-26 at 14-34-43 Feed Master

### CODE REVIEW

**Comment by umputun** [comment]
this is a useful addition, thx.

I would suggest extending each row a little bit, by adding a number of sources and the time of the last update. In addition, adding tg link (if present) would be nice as well. All of this is available as a part of `proc.Feed` you are passing into the template already

**Comment by orthur** [comment]
Updated page view

Screenshot 2022-03-26 at 22-14-14 Feed Master

**Comment by paskal** [comment]
"11 sources, 26 Mar 18:59" - I think, it might look clearer as "11 sources, last updated 26 March 2022 18:59".

**Comment by orthur** [comment]
Thanks, added

**Pull request merged**
